In [1]:
# 3. 신경망
# 3.5. 출력층 설계하기
# 3.5.3. 소프트맥스 함수의 특징 (p.94)
# 1 - 인터프리터

In [3]:
a = np.array([1010, 1000, 990]) # 소프트맥스 함수 계산
np.exp(a) / np.sum(np.exp(a)) # 계산되지 않는다.

C:\Users\bogyeongjang\AppData\Local\Temp\ipykernel_17260\832863605.py:2: RuntimeWarning: overflow encountered in exp
  np.exp(a) / np.sum(np.exp(a))
C:\Users\bogyeongjang\AppData\Local\Temp\ipykernel_17260\832863605.py:2: RuntimeWarning: invalid value encountered in divide
  np.exp(a) / np.sum(np.exp(a))


array([nan, nan, nan])

In [4]:
c = np.max(a)
a - c

array([  0, -10, -20])

In [5]:
np.exp(a - c) / sum(np.exp(a - c))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])