In [11]:
# 3. 신경망
# 3.3. 다차원 배열
# 3.3.3. 신경망의 내적 (p.82)

In [12]:
import numpy as np

In [13]:
X = np.array([1, 2])
X.shape

(2,)

In [14]:
W = np.array([[1, 3, 5], [2, 4, 6]])
print(W)

[[1 3 5]
 [2 4 6]]


In [15]:
W.shape

(2, 3)

In [16]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
